<?php

/**
 * Implements hook_date_ical_mapping_sources_alter()
 *
 * Adding the ATTENDEE:CN to map to a User
 */
function feeds_modify_date_ical_mapping_sources_alter(&$sources) {
  if ($source_id = 'classmate') {

    // Example of what might be done with this alter hook:
    // Add "ATTENDEE:CN" iCal property to the mapping sources
    $sources['ATTENDEE:CN'] = array(
        'name' => t('Attendee: CN'),
        'description' => t('The CN parameter of the ATTENDEE property: the attendee\'s Common Name.'),
        'date_ical_parse_handler' => 'parsePropertyParameter',
      );
    return $sources;
  }
}


/**
 * Overriding the value of location
 *
 */
function feeds_modify_feeds_after_parse(FeedsSource $source, FeedsParserResult $result) {
  if ($source->id == 'classmate') {
    $i = 1;
    foreach ($result->items as &$event) {

      log_to_file($i . " " . $event['ATTENDEE:CN']);
      $event['LOCATION'] = explode(',', $event['LOCATION']);
      $cat = $event['CATEGORIES'];
      $cat_ary = array();
      foreach($cat as $c){
        $term = taxonomy_term_load($c);
        array_push($cat_ary,$term->name);
      }
      $event['CATEGORIES'] = $cat_ary;

      $i++;
    }
  }
}
